package table_name

const (
	SysUser            string = "sys_user"
	SysDictType               = "sys_dict_type"
	SysDictData               = "sys_dict_data"
	SysDept                   = "sys_dept"
	SysMenu                   = "sys_menu"
	SysRole                   = "sys_role"
	SysRoleRelation           = "sys_role_relation"
	SysPost                   = "sys_post"
	SysPostRelation           = "sys_post_relation"
	SysLoginPolicy            = "sys_login_policy"
	SysOtpBind                = "sys_otp_bind"
	AssetGateway              = "asset_gateway"
	AssetGroup                = "asset_group"
	AssetBasic                = "asset_basic"
	AssetAccount              = "asset_account"
	AssetAccountExtend        = "asset_account_extend"
	AssetAuth                 = "asset_auth"
	SsoSession                = "sso_session"
	SsoOperation              = "sso_operation"
	ApproveCmd                = "approve_cmd"
	ApproveRecord             = "approve_record"
)
